# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 680)
        Form.setMinimumSize(QtCore.QSize(1000, 680))
        Form.setSizeIncrement(QtCore.QSize(1000, 680))
        self.pushButton_choosefile = QtWidgets.QPushButton(Form)
        self.pushButton_choosefile.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_choosefile.setFont(font)
        self.pushButton_choosefile.setStyleSheet("border:none")
        self.pushButton_choosefile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/78 open folder plus (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_choosefile.setIcon(icon)
        self.pushButton_choosefile.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_choosefile.setObjectName("pushButton_choosefile")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(610, 10, 61, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("border:none")
        self.pushButton_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/录音开启.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon1)
        self.pushButton_start.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_question = QtWidgets.QLabel(Form)
        self.label_question.setGeometry(QtCore.QRect(690, 15, 81, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_question.setFont(font)
        self.label_question.setScaledContents(True)
        self.label_question.setObjectName("label_question")
        self.pushButton_end = QtWidgets.QPushButton(Form)
        self.pushButton_end.setGeometry(QtCore.QRect(800, 10, 61, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_end.setFont(font)
        self.pushButton_end.setStyleSheet("border:none")
        self.pushButton_end.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/录音关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_end.setIcon(icon2)
        self.pushButton_end.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_end.setObjectName("pushButton_end")
        self.textEdit_question = QtWidgets.QTextEdit(Form)
        self.textEdit_question.setGeometry(QtCore.QRect(620, 110, 371, 101))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit_question.setFont(font)
        self.textEdit_question.setObjectName("textEdit_question")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(620, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(620, 300, 71, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setGeometry(QtCore.QRect(610, 240, 71, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("border:none")
        self.pushButton_ok.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ok.setIcon(icon3)
        self.pushButton_ok.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.textBrowser_question = QtWidgets.QTextBrowser(Form)
        self.textBrowser_question.setFont(font)
        self.textBrowser_question.setGeometry(QtCore.QRect(620, 340, 371, 331))
        self.textBrowser_question.setObjectName("textBrowser_question")
        self.label_mrc = QtWidgets.QLabel(Form)
        self.label_mrc.setGeometry(QtCore.QRect(710, 240, 71, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_mrc.setFont(font)
        self.label_mrc.setText("")
        self.label_mrc.setPixmap(QtGui.QPixmap("icon/结束.png"))
        self.label_mrc.setScaledContents(True)
        self.label_mrc.setObjectName("label_mrc")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_question.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Question"))
        self.label_3.setText(_translate("Form", "Answers"))

